#!/bin/bash
### Job Name
#PBS -N nwa25
#PBS -A URTG0024
#PBS -l walltime=9:12:00
#PBS -q regular
### Select 10 nodes with 36 CPUs 
#PBS -l select=99:ncpus=36:mpiprocs=36
### Send email on abort and end
#PBS -m ae
#PBS -M james.simkins@rutgers.edu

### Run the executable

#------------------------------------------------------------------------------------
# run the code - use qsub mom.sub to run, qstat -u jsimkins to check status
#------------------------------------------------------------------------------------

source /glade/work/jsimkins/runs-MOM6/nwa25/modules.sh

if [ ! -d RESTART ] ; then mkdir RESTART ; fi
rm ocean.stats.nc
cp /glade/work/jsimkins/MOM6-examples/build/intel/ice_ocean_SIS2/repro/MOM6 .

mpiexec_mpt dplace -s 1 /glade/work/jsimkins/runs-MOM6/nwa25/MOM6

